### PR TITLE
Mono

### LINKED ISSUE #4: Provide `mono-runtime`
openEuler does not provide an OS package for [mono-runtime](https://github.com/Bioconductor/BBS/blob/af1f643c3ed4ab6fb5f7d450b801f43812a35b88/Ubuntu-files/22.04/apt_bioc.txt#L29-L30)

Package `rawrr` fails due to this: 
* https://bio-arm.github.io/openeuler-0526/report/MsBackendRawFileReader/kunpeng2-install.html
* https://bio-arm.github.io/openeuler-0526/report/rawrr/kunpeng2-install.html

### PR DESCRIPTION
**Pull request by XingYuuuuu**
fixed https://github.com/bio-arm/bio-arm.github.io/issues/4

### CODE REVIEW

**Comment by XingYuuuuu** [comment]
Please take time to review the code. @martin-g @Yikun

**Review by martin-g — COMMENTED** [review]
The build has failed: https://eur.openeuler.openatom.cn/results/XingYuuuuu/biocondutor/openeuler-23.03-aarch64/00090340-mono/builder-live.log.gz

```
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.QGRauQ
+ umask 022
+ cd /builddir/build/BUILD
+ cd /builddir/build/BUILD
+ rm -rf mono-6.12.0.182
+ /usr/lib/rpm/rpmuncompress -x /builddir/build/SOURCES/mono-mono-6.12.0.182.tar.gz
+ STATUS=0
+ '[' 0 -ne 0 ']'

RPM build errors:
+ cd mono-6.12.0.182
/var/tmp/rpm-tmp.QGRauQ: line 38: cd: mono-6.12.0.182: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.QGRauQ (%prep)
    Bad exit status from /var/tmp/rpm-tmp.QGRauQ (%prep)
```

**Comment by martin-g** [comment]
The log file contains `INFO: Reading stdout from command: md5sum mono-mono-6.12.0.182.tar.gz` but the `Source0` downloads http://download.mono-project.com/sources/mono/mono-%{version}.%{xamarinrelease}.tar.xz. Note the `.gz` versus `.xz` file extension! I don't get it where the `.gz` file comes from.

**Comment by martin-g** [comment]
It seems the latest build is for the commit before this one - https://github.com/bio-arm/rpms/pull/9/commits/e587b957319f9f81042bf4c380e8e6924ea042dd
@XingYuuuuu Please run a new build against the latest version at Git!

**Pull request closed without merging**
